GDAES-707 backwards conditional, wow

diff --git a/templates/default/user-data.sh.erb b/templates/default/user-data.sh.erb
--- a/templates/default/user-data.sh.erb
+++ b/templates/default/user-data.sh.erb
@@ -1,6 +1,9 @@
 #!/bin/bash
 results=`curl http://169.254.169.254/latest/user-data/ --connect-timeout 3`
 if [[ `echo $results | grep -c 404` -gt 0 || -z $results ]]; then
+  echo "ERROR: Response was |${results}|"
+  exit 1
+else
   echo $results > aws-userdata.sh
   sed -i 's/\r//' aws-userdata.sh
   chmod +x aws-userdata.sh
